  kafka:
    order:
      bootstrap-servers: ${KAFKA_RESERVATION_BOOTSTRAP_SERVERS:localhost:9092}
      topic:
        create-order: create-order
      consumer:
        group-id:
          notification: notification
          service: service